### ISSUE TITLE
Complete results to share?

### ISSUE THREAD

**Issue by m-cameron** [francesco1119/Fantail#5]
Do you have a complete results to share?

**Comment by francesco1119** [comment]
Result from what? 
What are you looking for?

**Comment by m-cameron** [comment]
The data you collected from Google Places you used to plot those maps. So that we know the outputs of the libraries if it is working properly.

**Comment by francesco1119** [comment]
All cinemas in NZ.

[NZ_Cinemas.txt](https://github.com/francesco1119/Fantail/files/2537727/NZ_Cinemas.txt)
